### ISSUE TITLE
Fault with class method cueTypeIsAudio

### ISSUE THREAD

**Issue by Daniel-Higgott** [Figure53/QLabKit.objc#19]
Hello,

I have discovered that cueTypeIsAudio still returns 'true' for video cues in 0.0.4.

Cheers,

Dan

**Comment by balord** [comment]
Hi Dan -

The name is perhaps a bit misleading, but that is the intended behavior for that method since Video cues also can have audio features. You could read the word "is" in those class method names to mean "supports". For example, when viewing a cue in the inspector, QLab Remote uses `cueTypeIsAudio` to determine whether to display the audio sliders panel and `cueTypeIsVideo` to determine whether to display the geometry controls.

There are cases where, depending upon the media it is playing, a specific Video cue might not have audio features enabled, e.g. if it is playing back a still image. But the QLab OSC dictionary does not currently provide a way to clearly determine if a Video cue has a still-image source, so QLabKit `cueTypeIsAudio` returns `YES` for all Video cues to be safe.

To determine the precise cue type, you can always test the QLKCue `type` property for one of the `QLKCueType*` constants found in [QLKDefines.h](https://github.com/Figure53/QLabKit.objc/blob/0.0.4/lib/QLKDefines.h#L57).
